settings:
  title: 'Status Page'
  url: 'https://status.andp97.dev' # used for Slack messages
  logo: logo_andrea.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: andreapavone-com # unique identifier
    name: andreapavone.com
    description: 'Personal Web Site' # default=empty
    url: 'https://andreapavone.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: ip-andreapavone-com
    name: ip.andreapavone.com
    description: 'MyIp Info'
    url: 'https://ip.andreapavone.com'
    method: GET
    expectStatus: 200
